// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT7tStkp5IL28y0RKBDSZqxTGnSLSOuHU',
    appId: '1:977162283055:web:0e76916820a06bc9d53eda',
    messagingSenderId: '977162283055',
    projectId: 'mobile44-35be6',
    authDomain: 'mobile44-35be6.firebaseapp.com',
    storageBucket: 'mobile44-35be6.appspot.com',
    measurementId: 'G-1C9D93PMJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhXaOWZHnlAAwJRv5lgzG6PG7cnYkGAc',
    appId: '1:977162283055:android:54664826b2934c38d53eda',
    messagingSenderId: '977162283055',
    projectId: 'mobile44-35be6',
    storageBucket: 'mobile44-35be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZeomQ1EyJuUEwdJ06WKPRNpx5tkhPXM',
    appId: '1:977162283055:ios:60cbc20944d387fad53eda',
    messagingSenderId: '977162283055',
    projectId: 'mobile44-35be6',
    storageBucket: 'mobile44-35be6.appspot.com',
    androidClientId: '977162283055-q95q5ns7gmest4agehimj187avulfqlp.apps.googleusercontent.com',
    iosClientId: '977162283055-7qreidus9598dj2gqi0cf2c8o9i16lsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkZeomQ1EyJuUEwdJ06WKPRNpx5tkhPXM',
    appId: '1:977162283055:ios:d57943f859433060d53eda',
    messagingSenderId: '977162283055',
    projectId: 'mobile44-35be6',
    storageBucket: 'mobile44-35be6.appspot.com',
    androidClientId: '977162283055-q95q5ns7gmest4agehimj187avulfqlp.apps.googleusercontent.com',
    iosClientId: '977162283055-ai3tjtlfl1jnbuk9ovp78kdcerel9158.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile1.RunnerTests',
  );
}
